"use client";
import "./globals.css";
import { Inter } from "next/font/google";
import { MantineProvider } from "@mantine/core";
import { Notifications } from "@mantine/notifications";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <MantineProvider withGlobalStyles withNormalizeCSS>
                <body className={inter.className}>{children}</body>
                <Notifications />
            </MantineProvider>
        </html>
    );
}
