import "./globals.css";
import { Inter } from "next/font/google";
import { Metadata } from "next";
import { AppProvider } from "./provider";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "JWT Authentication with Next.js Demo",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <AppProvider>{children}</AppProvider>
                <Toaster position="bottom-right" reverseOrder={false} />
            </body>
        </html>
    );
}
